### ISSUE TITLE
Provision Sql Server and Web App in Azure

### ISSUE THREAD

**Issue by mdwmax** [EduShareOntario/Academic-and-Career-Prep#1]

**Comment by ThomasLamb** [comment]
E-mail Grant request for SQL Server database and Web App in Azure.

**Comment by ThomasLamb** [comment]
In conversation with Ops to try and get resources setup in Azure. I'm providing them with information about the existing environment.

**Comment by ThomasLamb** [comment]
A rough cost estimate has been provided to department, Ops has been told to start creating the servers.

**Comment by ThomasLamb** [comment]
Azure Web App and SQL have been created.
