### ISSUE TITLE
Database creation?

### ISSUE THREAD

**Issue by ThomasLamb** [EduShareOntario/Academic-and-Career-Prep#39]
Hey @NickRowlandson, can you add the database creation scripts? Or explain how you initially created the database? When the Azure server is created I'll create the database and site.

**Comment by NickRowlandson** [comment]
[DB Scripts.zip](https://github.com/EduShareOntario/Academic-and-Career-Prep/files/1839549/DB.Scripts.zip)
Thanks @ThomasLamb, here are the scripts for creating the tables. All I did in Azure to create the database was click 'Create a resource' top left, then select 'SQL Database'.
