### ISSUE TITLE
Prompt for staff to select new password at first log in, to enhance security

### ISSUE THREAD

**Issue by patriciawhittington** [EduShareOntario/Academic-and-Career-Prep#8]

**Comment by jimdonald** [comment]
We will need the ability to recover a password.

**Comment by patriciawhittington** [comment]
What is this?

Pat

Patricia Whittington, M.Ed.
Director, Indigenous Services and Access Programs
Georgian College | One Georgian Drive | Barrie ON | L4M 3X9
705.728.1968, ext. 1080 | GeorgianCollege.ca<http://www.georgiancollege.ca/?utm_source=General&utm_campaign=Email_Signature&utm_medium=email>

[Georgian College]<http://www.georgiancollege.ca/celebrate50/?utm_source=Celebrate50&utm_campaign=Email_Signature&utm_medium=email>

**Comment by jimdonald** [comment]
I was making a comment on Waffle for Nick.

Fyi my computer will not let me email. It all goes to my outbox I am not ignoring you. ;-)

Jim Donald
Program Co-ordinator, Academic and Career Preparation
One Georgian Drive, Barrie
705.7281968. Ext. 1614
From: patriciawhittington
Sent: Tuesday, December 5, 2017 12:09 PM
To: EduShareOntario/Academic-and-Career-Prep
Reply To: EduShareOntario/Academic-and-Career-Prep
Cc: Jim Donald; Comment
Subject: Re: [EduShareOntario/Academic-and-Career-Prep] Prompt for staff to select new password at first log in, to enhance security (#8)


What is this?

Pat

Patricia Whittington, M.Ed.
Director, Indigenous Services and Access Programs
Georgian College | One Georgian Drive | Barrie ON | L4M 3X9
705.728.1968, ext. 1080 | GeorgianCollege.ca<http://www.georgiancollege.ca/?utm_source=General&utm_campaign=Email_Signature&utm_medium=email>

[Georgian College]<http://www.georgiancollege.ca/celebrate50/?utm_source=Celebrate50&utm_campaign=Email_Signature&utm_medium=email>

**Comment by jimdonald** [comment]
I just put this comment into Waffle for Nick. I am just going over the requests made over the last while.

Jim
